apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: default
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.elastic.co/logstash/logstash:8.7.0
        ports:
        - containerPort: 5044
        volumeMounts:
        - name: logstash-config-volume
          mountPath: /usr/share/logstash/pipeline/logstash.conf
          subPath: logstash.conf
        - name: desktop-log
          mountPath: /usr/share/logstash/logs/backend.log
          subPath: backend.log
        resources:
          limits:
            memory: 1Gi
            cpu: 500m
          requests:
            memory: 512Mi
            cpu: 250m
      volumes:
      - name: logstash-config-volume
        configMap:
          name: logstash-config
      - name: desktop-log
        hostPath:
          path: /home/abheet/Desktop/backend.log
          type: File
---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: default
spec:
  selector:
    app: logstash
  ports:
  - protocol: TCP
    port: 5044
    targetPort: 5044
  type: ClusterIP
